version: '3'
services:
  my-python-app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app

    ports:
      - 8000:8000

    depends_on: 
      - redis

  my-react-app:
    build: 
      context: ./frontend  # Asegúrate de reemplazar esto con el camino correcto a tu app React
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app    # Asegúrate de reemplazar esto con el camino correcto a tu app React
    ports:
      - 5173:5173

  redis:
    image: redis:7.2-rc3-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
