version: '3'
services:
  my-python-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/app

    ports:
      - 80:80

    depends_on:
      - redis

  my-react-app:
    build:
      context: ./frontend # Asegúrate de reemplazar esto con el camino correcto a tu app React
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend:/app # Asegúrate de reemplazar esto con el camino correcto a tu app React
    ports:
      - 5173:5173

  redis:
    image: redis:7.2-rc3-alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
