version: '3'
services:
  my-python-app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app

    ports:
      - 8000:8000

    depends_on: 
      - redis

  redis:
    image: redis:7.2-rc3-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  redis_data:
